export * from "./botVaultV3.lifecycle.js";

import {
  assertBotVaultV3FundingLifecycleTransition,
  buildBotVaultV3FundingLifecycleTransitionPatch,
  classifyBotVaultV4Mismatch,
  classifyBotVaultV4Status,
  compareBotVaultV3FundingLifecycleStage,
  createBotVaultV3FundingLifecycleMetadata,
  deriveBotVaultV4RecoveryHint,
  findBotVaultV3FundingLifecyclePath,
  getBotVaultV3FundingLifecycleProgressIndex,
  getBotVaultV3FundingLifecycleStage,
  hasBotVaultV3FundingReadiness,
  normalizeBotVaultV4MismatchCategory,
  normalizeBotVaultV4MismatchRecoveryAction,
  normalizeBotVaultV4RecoveryHint,
  normalizeBotVaultV4StatusCategory,
  readBotVaultV3FundingLifecycleState,
  type BotVaultV3FundingLifecycleStage,
  type BotVaultV3FundingLifecycleState,
  type BotVaultV3FundingLifecycleTransition,
  type BotVaultV4MismatchCategory,
  type BotVaultV4MismatchClassification,
  type BotVaultV4MismatchRecoveryAction,
  type BotVaultV4RecoveryHint,
  type BotVaultV4StatusCategory,
  type BotVaultV4StatusDescriptor
} from "./botVaultV3.lifecycle.js";

export type BotVaultFundingLifecycleStage = BotVaultV3FundingLifecycleStage;
export type BotVaultFundingLifecycleState = BotVaultV3FundingLifecycleState;
export type BotVaultFundingLifecycleTransition = BotVaultV3FundingLifecycleTransition;
export type BotVaultRuntimeMismatchCategory = BotVaultV4MismatchCategory;
export type BotVaultRuntimeMismatchClassification = BotVaultV4MismatchClassification;
export type BotVaultRuntimeMismatchRecoveryAction = BotVaultV4MismatchRecoveryAction;
export type BotVaultRuntimeRecoveryHint = BotVaultV4RecoveryHint;
export type BotVaultRuntimeStatusCategory = BotVaultV4StatusCategory;
export type BotVaultRuntimeStatusDescriptor = BotVaultV4StatusDescriptor;
export type BotVaultV4FundingLifecycleStage = BotVaultFundingLifecycleStage;
export type BotVaultV4FundingLifecycleState = BotVaultFundingLifecycleState;
export type BotVaultV4FundingLifecycleTransition = BotVaultFundingLifecycleTransition;

export const assertBotVaultFundingLifecycleTransition = assertBotVaultV3FundingLifecycleTransition;
export const buildBotVaultFundingLifecycleTransitionPatch = buildBotVaultV3FundingLifecycleTransitionPatch;
export const classifyBotVaultRuntimeMismatch = classifyBotVaultV4Mismatch;
export const classifyBotVaultRuntimeStatus = classifyBotVaultV4Status;
export const compareBotVaultFundingLifecycleStage = compareBotVaultV3FundingLifecycleStage;
export const createBotVaultFundingLifecycleMetadata = createBotVaultV3FundingLifecycleMetadata;
export const deriveBotVaultRuntimeRecoveryHint = deriveBotVaultV4RecoveryHint;
export const findBotVaultFundingLifecyclePath = findBotVaultV3FundingLifecyclePath;
export const getBotVaultFundingLifecycleProgressIndex = getBotVaultV3FundingLifecycleProgressIndex;
export const getBotVaultFundingLifecycleStage = getBotVaultV3FundingLifecycleStage;
export const hasBotVaultFundingReadiness = hasBotVaultV3FundingReadiness;
export const normalizeBotVaultRuntimeMismatchCategory = normalizeBotVaultV4MismatchCategory;
export const normalizeBotVaultRuntimeMismatchRecoveryAction = normalizeBotVaultV4MismatchRecoveryAction;
export const normalizeBotVaultRuntimeRecoveryHint = normalizeBotVaultV4RecoveryHint;
export const normalizeBotVaultRuntimeStatusCategory = normalizeBotVaultV4StatusCategory;
export const readBotVaultFundingLifecycleState = readBotVaultV3FundingLifecycleState;
export const assertBotVaultV4FundingLifecycleTransition = assertBotVaultFundingLifecycleTransition;
export const buildBotVaultV4FundingLifecycleTransitionPatch = buildBotVaultFundingLifecycleTransitionPatch;
export const compareBotVaultV4FundingLifecycleStage = compareBotVaultFundingLifecycleStage;
export const createBotVaultV4FundingLifecycleMetadata = createBotVaultFundingLifecycleMetadata;
export const findBotVaultV4FundingLifecyclePath = findBotVaultFundingLifecyclePath;
export const getBotVaultV4FundingLifecycleProgressIndex = getBotVaultFundingLifecycleProgressIndex;
export const getBotVaultV4FundingLifecycleStage = getBotVaultFundingLifecycleStage;
export const hasBotVaultV4FundingReadiness = hasBotVaultFundingReadiness;
export const readBotVaultV4FundingLifecycleState = readBotVaultFundingLifecycleState;
