export type OnchainTxRequest = {
  to: `0x${string}`;
  data: `0x${string}`;
  value: string;
  chainId: number;
};

export type OnchainActionType =
  | "create_master_vault"
  | "deposit_master_vault"
  | "withdraw_master_vault"
  | "create_bot_vault"
  | "reserve_for_bot_vault"
  | "fund_bot_vault_hypercore"
  | "set_bot_vault_close_only"
  | "set_bot_vault_agent_wallet"
  | "claim_from_bot_vault"
  | "close_bot_vault"
  | "create_bot_vault_v3"
  | "fund_bot_vault_v3"
  | "claim_profit_bot_vault_v3"
  | "close_bot_vault_v3"
  | "create_bot_vault_v4"
  | "fund_bot_vault_v4"
  | "claim_profit_bot_vault_v4"
  | "close_bot_vault_v4"
  | "recover_closed_bot_vault"
  | "funding_bridge_deposit"
  | "funding_bridge_withdraw"
  | "funding_transfer_core_to_evm"
  | "funding_transfer_evm_to_core"
  | "funding_usd_class_transfer"
  | "set_treasury_recipient"
  | "set_profit_share_fee_rate"
  | "create_funding_vault"
  | "deposit_funding_vault"
  | "withdraw_funding_vault"
  | "agent_withdraw_funding_vault"
  | "launch_bot_vault_from_funding_vault"
  | "fund_bot_vault_from_funding_vault";

export interface OnchainProvider {
  buildCreateMasterVaultTx(input: {
    ownerAddress: `0x${string}`;
  }): Promise<OnchainTxRequest>;
  buildDepositToMasterVaultTx(input: {
    masterVaultAddress: `0x${string}`;
    amountAtomic: bigint;
  }): Promise<OnchainTxRequest>;
  buildWithdrawFromMasterVaultTx(input: {
    masterVaultAddress: `0x${string}`;
    amountAtomic: bigint;
  }): Promise<OnchainTxRequest>;
  buildCreateBotVaultTx(input: {
    masterVaultAddress: `0x${string}`;
    templateId: string;
    botId: string;
    allocationAtomic: bigint;
    agentWallet?: `0x${string}`;
  }): Promise<OnchainTxRequest>;
  buildReserveForBotVaultTx(input: {
    masterVaultAddress: `0x${string}`;
    botVaultAddress: `0x${string}`;
    amountAtomic: bigint;
  }): Promise<OnchainTxRequest>;
  buildFundBotVaultOnHyperCoreTx(input: {
    masterVaultAddress: `0x${string}`;
    botVaultAddress: `0x${string}`;
    amountAtomic: bigint;
  }): Promise<OnchainTxRequest>;
  buildSetBotVaultCloseOnlyTx(input: {
    masterVaultAddress: `0x${string}`;
    botVaultAddress: `0x${string}`;
  }): Promise<OnchainTxRequest>;
  buildSetBotVaultAgentWalletTx(input: {
    masterVaultAddress: `0x${string}`;
    botVaultAddress: `0x${string}`;
    agentWallet: `0x${string}`;
  }): Promise<OnchainTxRequest>;
  buildSetTreasuryRecipientTx(input: {
    treasuryRecipient: `0x${string}`;
  }): Promise<OnchainTxRequest>;
  buildSetProfitShareFeeRateTx(input: {
    feeRatePct: bigint;
  }): Promise<OnchainTxRequest>;
  buildClaimFromBotVaultTx(input: {
    masterVaultAddress: `0x${string}`;
    botVaultAddress: `0x${string}`;
    releasedReservedAtomic: bigint;
    grossReturnedAtomic: bigint;
  }): Promise<OnchainTxRequest>;
  buildCloseBotVaultTx(input: {
    masterVaultAddress: `0x${string}`;
    botVaultAddress: `0x${string}`;
    releasedReservedAtomic: bigint;
    grossReturnedAtomic: bigint;
  }): Promise<OnchainTxRequest>;
  buildRecoverClosedBotVaultTx(input: {
    masterVaultAddress: `0x${string}`;
    botVaultAddress: `0x${string}`;
    releasedReservedAtomic: bigint;
    grossReturnedAtomic: bigint;
  }): Promise<OnchainTxRequest>;
  buildCreateBotVaultV3Tx?(input: {
    beneficiaryAddress: `0x${string}`;
    controllerAddress: `0x${string}`;
    agentWallet?: `0x${string}`;
    templateId: string;
    botId: string;
    profitShareFeeRatePct?: bigint;
    platformFeeRatePct?: bigint;
    affiliateFeeRatePct?: bigint;
    affiliateRecipientAddress?: `0x${string}`;
  }): Promise<OnchainTxRequest>;
  buildFundBotVaultV3Tx?(input: {
    botVaultAddress: `0x${string}`;
    amountAtomic: bigint;
  }): Promise<OnchainTxRequest>;
  buildClaimProfitBotVaultV3Tx?(input: {
    botVaultAddress: `0x${string}`;
    grossAmountAtomic: bigint;
    feeAmountAtomic: bigint;
    principalPortionAtomic: bigint;
    realizedClosedPnlAtomic?: bigint;
  }): Promise<OnchainTxRequest>;
  buildCloseBotVaultV3Tx?(input: {
    botVaultAddress: `0x${string}`;
    principalToReturnAtomic: bigint;
    grossAmountAtomic: bigint;
    feeAmountAtomic: bigint;
    realizedClosedPnlAtomic?: bigint;
  }): Promise<OnchainTxRequest>;
  buildSetBotVaultV3CloseOnlyTx?(input: {
    botVaultAddress: `0x${string}`;
  }): Promise<OnchainTxRequest>;
  buildSetBotVaultV3AgentWalletTx?(input: {
    botVaultAddress: `0x${string}`;
    agentWallet: `0x${string}`;
  }): Promise<OnchainTxRequest>;
}
