export const BINGX_USDM_DEFAULT_REST_BASE_URL = "https://open-api.bingx.com";
export const BINGX_USDM_DEFAULT_PRODUCT_TYPE = "USDT-FUTURES";
export const BINGX_USDM_DEFAULT_MARGIN_COIN = "USDT";
export const BINGX_USDM_DEFAULT_RECV_WINDOW_MS = 5_000;
export const BINGX_USDM_DEFAULT_TIMEOUT_MS = 15_000;
export const BINGX_USDM_DEFAULT_RETRY_ATTEMPTS = 3;
export const BINGX_USDM_DEFAULT_RETRY_BASE_DELAY_MS = 350;
